### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by jamesjer** [miguelmarco/SIROCCO2#1]
The LICENSE file contains the text of GPL version 3, but only ZVK.py contains any kind of license statement, and it specifies GPL version 2 or later.  Please add the GPL boilerplate text to the remaining source files so that the exact acceptable version or versions of the GPL are made clear.

Note that Fedora, for example, says that the lack of clear statement means the sources are covered by *any* version of the GPL.  Search for "GPL+" here: https://fedoraproject.org/wiki/Licensing:Main?rd=Licensing#SoftwareLicenses.

**Comment by miguelmarco** [comment]
The whole project is GPLv3. The file ZVK.py is under GPLv2 because it is part of Sage the distribution (it is included in the last versions, under a different name). 

Would it be enough to remove the GPLv2+ bolierplate from that specific file to make the LICENSE statement cover all the files in the project?

**Comment by jamesjer** [comment]
My apologies.  I somehow managed to overlook your reply, for 4 years!  It would be enough to put some kind of statement in, say README.md.  Something like this would be suitable: "Sirocco is released under the terms of the GPL, version 3.0, as described in LICENSE."

**Comment by miguelmarco** [comment]
Done.
